version: "3.4"
services:
  web:
    image: k3v1nn90/tapi
    ports:
      - "5000:5000"
    networks:
      - webnet
  redis:
    image: redis
    networks:
      - webnet
networks:
  webnet: